package domain

import "time"

type ManifestStatus string

const (
	ManifestComplete    ManifestStatus = "COMPLETE"
	ManifestPartial     ManifestStatus = "PARTIAL"
	ManifestUnavailable ManifestStatus = "UNAVAILABLE"
)

type AnalysisProfile string

const (
	ProfileOff      AnalysisProfile = "off"
	ProfileAssist   AnalysisProfile = "assist"
	ProfileVerified AnalysisProfile = "verified"
)

// AnalysisBinding associates research findings with exact versions and hashes.
type AnalysisBinding struct {
	AdvisoryID           string `json:"advisory_id"`
	AdvisoryHash         string `json:"advisory_hash"`
	Module               string `json:"module"`
	ResolvedVersion      string `json:"resolved_version"`
	VulnerableSourceHash string `json:"vulnerable_source_hash,omitempty"`
	FixManifestHash      string `json:"fix_manifest_hash,omitempty"`
}

// SourceArtifact describes a fetched artifact.
type SourceArtifact struct {
	ID          string     `json:"id"`
	Side        string     `json:"side"` // "vulnerable", "fixed", "patch"
	URI         string     `json:"uri"`
	Commit      string     `json:"commit,omitempty"`
	Hash        string     `json:"hash"`
	Status      string     `json:"status"` // "FETCHED", "FAILED", "TRUNCATED"
	EvidenceID  EvidenceID `json:"evidence_id,omitempty"`
	Truncated   bool       `json:"truncated,omitempty"`
	Limitations []string   `json:"limitations,omitempty"`
}

// CVESourceBundle holds artifacts for offline library analysis.
type CVESourceBundle struct {
	Binding        AnalysisBinding  `json:"binding"`
	Artifacts      []SourceArtifact `json:"artifacts,omitempty"`
	SourceDir      string           `json:"source_dir,omitempty"`
	PatchDiff      string           `json:"patch_diff,omitempty"`
	ManifestStatus ManifestStatus   `json:"manifest_status"`
	Limitations    []string         `json:"limitations,omitempty"`
	FetchedAt      time.Time        `json:"fetched_at"`
}

// DefectMechanism represents extracted defect details.
type DefectMechanism struct {
	ID               string   `json:"id"`
	Summary          string   `json:"summary"`
	FaultingSites    []string `json:"faulting_sites"`
	AuxiliarySites   []string `json:"auxiliary_sites,omitempty"`
	PatchExplanation string   `json:"patch_explanation"`
}

// CVEAnalysisProposal is the hypothesis generated by the researcher.
type CVEAnalysisProposal struct {
	ID             string            `json:"id"`
	Revision       int               `json:"revision"`
	Binding        AnalysisBinding   `json:"binding"`
	Mechanisms     []DefectMechanism `json:"mechanisms"`
	Preconditions  []string          `json:"preconditions,omitempty"`
	Confidence     string            `json:"confidence"` // "HIGH", "MEDIUM", "LOW"
	EvidenceIDs    []EvidenceID      `json:"evidence_ids,omitempty"`
	ToolIterations int               `json:"tool_iterations"`
}

// SemanticReview is the result of independent mechanism review.
type SemanticReview struct {
	Passed      bool         `json:"passed"`
	Reviewer    string       `json:"reviewer"`
	Findings    []string     `json:"findings,omitempty"`
	EvidenceIDs []EvidenceID `json:"evidence_ids,omitempty"`
}

// StrategyPlan documents the planned verification strategy.
type StrategyPlan struct {
	ID               string   `json:"id"`
	SelectedStrategy string   `json:"selected_strategy"`
	Obligations      []string `json:"obligations"`
	StopReason       string   `json:"stop_reason,omitempty"`
}

// HumanRemainderItem is an unresolved obligation that requires expert confirmation.
type HumanRemainderItem struct {
	Obligation  string `json:"obligation"`
	Question    string `json:"question"`
	EvidenceRef string `json:"evidence_ref,omitempty"`
}

// ProductExposureFacts captures observed facts about constructor and package linkage.
type ProductExposureFacts struct {
	EntrypointConstructors []string `json:"entrypoint_constructors,omitempty"`
	AbsentConstructors     []string `json:"absent_constructors,omitempty"`
	LinkedPackages         []string `json:"linked_packages,omitempty"`
	UnlinkedPackages       []string `json:"unlinked_packages,omitempty"`
}

// AnalysisJustification is the audit-ready dossier explaining the findings.
type AnalysisJustification struct {
	VulnerabilityID    string               `json:"vulnerability_id"`
	Verdict            Verdict              `json:"verdict"`
	ExecutiveSummary   string               `json:"executive_summary"`
	TechnicalMechanism string               `json:"technical_mechanism"`
	ProductExposure    ProductExposureFacts `json:"product_exposure"`
	VerifiedFacts      []string             `json:"verified_facts,omitempty"`
	HumanRemainder     []HumanRemainderItem `json:"human_remainder,omitempty"`
	TrackerCommentRu   string               `json:"tracker_comment_ru"`
}
